#!/bin/bash
# Quick Start with HTTPS/SSL

echo "================================"
echo "HTTPS/SSL Setup Complete ✓"
echo "================================"
echo ""

echo "Generated SSL Certificates:"
echo "  ✓ /Users/ifocus/Documents/kill/cert/cert.pem (Certificate)"
echo "  ✓ /Users/ifocus/Documents/kill/cert/key.pem (Private Key)"
echo ""

echo "Backend Configuration:"
echo "  ✓ Updated: ./backend/run_backend.sh (now uses --ssl-keyfile and --ssl-certfile)"
echo "  ✓ Updated: ./backend/.env (TWILIO_WEBHOOK_URL=https://localhost:3003)"
echo "  ✓ Updated: ./backend/.env (VITE_API_BASE_URL=https://localhost:3003)"
echo ""

echo "Frontend Configuration:"
echo "  ✓ Updated: ./frontend/vite.config.js (server.https with SSL certs)"
echo ""

echo "================================"
echo "To Start the Application:"
echo "================================"
echo ""

echo "Terminal 1 - Start Backend:"
echo "  cd /Users/ifocus/Documents/kill/backend"
echo "  ./run_backend.sh"
echo ""

echo "Terminal 2 - Start Frontend:"
echo "  cd /Users/ifocus/Documents/kill/frontend"
echo "  npm run dev"
echo ""

echo "================================"
echo "Important Notes:"
echo "================================"
echo ""
echo "1. Backend will run on: https://localhost:3003"
echo "2. Frontend will run on: https://localhost:5173"
echo ""
echo "3. Browser SSL Warning:"
echo "   - This is NORMAL for self-signed certificates"
echo "   - Click 'Advanced' and 'Proceed to localhost'"
echo ""
echo "4. Twilio Webhooks (IMPORTANT):"
echo "   - Twilio cannot reach localhost URLs"
echo "   - To use Twilio callbacks, tunnel localhost with ngrok:"
echo "     ngrok http https://localhost:3003"
echo "   - Update TWILIO_WEBHOOK_URL in .env to the ngrok URL"
echo ""
echo "================================"
echo "Setup documentation in: /Users/ifocus/Documents/kill/HTTPS_SETUP.md"
echo "================================"
